#ifndef tiny_multipart_h
#define tiny_multipart_h

#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdarg>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>


namespace tiny_multipart {

/// Result of advancing a parser through the C API.
enum class RetCode : uint8_t {
  /// An entry was written to the output pointer.
  Ok = 0,
  /// The parser reached the closing boundary.
  Eos = 1,
  /// The input or parser state is invalid.
  Error = 2,
};

/// Opaque multipart parser for the C API.
struct Parser;

/// A slice of bytes as seen from C.
struct Slice {
  /// Pointer to the first byte, or null when `len` is zero.
  const uint8_t *data;
  /// Number of bytes in the slice.
  size_t len;
};

/// A C view of a parsed entry. For optional fields, a NULL data pointer means not present.
struct Entry {
  /// The entry's `name` parameter.
  Slice name;
  /// The raw entry body.
  Slice value;
  /// The optional `filename` parameter.
  Slice filename;
  /// The optional `Content-Type` header.
  Slice content_type;
};


extern "C" {

/// Creates a new parser with the provided data.
///
/// # Safety
///
/// `data` must point to a valid [`Slice`]. Its bytes must remain valid for the
/// lifetime of the returned parser and must not be modified, including by
/// another thread, during that time. `boundary` must point to a
/// NUL-terminated string for the duration of this call.
Parser *tiny_multipart_parser_new(const Slice *data, const char *boundary);

/// Frees a parser created by [`tiny_multipart_parser_new`].
///
/// # Safety
///
/// `parser` must be null or a pointer returned by
/// [`tiny_multipart_parser_new`] that has not already been freed.
void tiny_multipart_parser_free(Parser *parser);

/// Retrieve the next entry from the parser into provided entry.
///
/// # Safety
///
/// `parser` must point to a live parser and `entry` must point to writable
/// memory for one [`Entry`].
RetCode tiny_multipart_parser_next(Parser *parser, Entry *entry);

/// Retrieves the boundary from a Content-Type header.
///
/// # Safety
///
/// `content_type` must point to a valid [`Slice`]. Its backing bytes must
/// remain valid and immutable while the returned boundary slice is used.
/// `boundary` must point to writable memory for one [`Slice`]. The descriptor
/// pointers may alias.
void tiny_multipart_boundary_from_content_type(const Slice *content_type, Slice *boundary);

}  // extern "C"

}  // namespace tiny_multipart

#endif  // tiny_multipart_h
